# Generated by Django 4.1.5 on 2023-01-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product-thumbnail'),
        ),
    ]
