# Generated by Django 4.1.5 on 2023-01-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endorsers', '0001_initial'),
        ('organizations', '0002_project_organization'),
        ('authentication', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_endorser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='endorsers.endorser'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.staff'),
        ),
    ]
