# Generated by Django 4.1.5 on 2023-01-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endorsers', '0001_initial'),
        ('organizations', '0004_staff_user'),
        ('authentication', '0004_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_endorser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorser_object', to='endorsers.endorser'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_object', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_member_object', to='organizations.staff'),
        ),
    ]
