# Generated by Django 4.1.5 on 2023-02-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_alter_review_options_user_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="refer_id",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
