# Generated by Django 4.1.5 on 2023-02-25 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_user_refer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=2)),
                ("register_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_joined",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_joined",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
