# Generated by Django 4.1.5 on 2023-01-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorser',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
