# Generated by Django 4.1.5 on 2023-01-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsers', '0002_endorser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorser',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
