# Generated by Django 4.1.5 on 2023-01-22 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endorsers', '0005_order_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
