# Generated by Django 4.1.5 on 2023-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endorsers", "0007_orderupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="endorser",
            name="price",
            field=models.IntegerField(default=300),
        ),
    ]
