# Generated by Django 4.1.5 on 2023-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endorsers", "0008_endorser_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="endorser",
            name="reviews",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="endorser",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
