# Generated by Django 4.1.5 on 2023-03-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endorsers", "0009_endorser_reviews_alter_endorser_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="endorser",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
