# Generated by Django 4.1.5 on 2023-03-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endorsers', '0011_remove_endorser_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endorser',
            name='rating',
        ),
    ]
