# Generated by Django 4.1.5 on 2023-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endorsers', '0012_remove_endorser_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='endorser',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
