# Generated by Django 4.1.5 on 2023-05-19 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='survey_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
