# Generated by Django 4.1.5 on 2023-05-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyresponse_survey_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='next_question_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
