# Generated by Django 4.1.5 on 2023-05-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='subsection',
            options={'ordering': ('id',)},
        ),
    ]
