# Generated by Django 4.1.5 on 2023-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_question_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.FloatField(),
        ),
    ]
