# Generated by Django 4.1.5 on 2023-06-09 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_question_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='SectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=255)),
                ('section_reports', models.ManyToManyField(to='surveys.sectionreport')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='surveys.surveyresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
