# Generated by Django 4.1.5 on 2023-06-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_report_section_reports_suggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='point_to_add',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
