# Generated by Django 4.1.5 on 2023-04-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
