# Generated by Django 4.1.5 on 2023-04-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_remove_skill_slug_skillcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='slug',
        ),
    ]
