# Generated by Django 4.1.5 on 2023-04-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_attempt_badge_wonbadge_quiz_question_attempt_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='badge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.badge'),
        ),
    ]
