# Generated by Django 4.1.5 on 2023-04-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_quiz_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='quiz_added',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
