# Generated by Django 4.1.5 on 2023-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_skill_quiz_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
