# Generated by Django 4.1.5 on 2023-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_alter_attempt_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='is_report_generated',
            field=models.BooleanField(default=False),
        ),
    ]
