# Generated by Django 4.1.5 on 2023-04-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_attempt_is_report_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
